create table mkt_google_ads(
    mkt_google_ads_id int not null auto_increment primary key,
    campaign_id int,
    campaign_name varchar(200),
    campaign_status int,
    campaign_start_date date,
    campaign_end_date date,
    group_id int,
    group_name varchar(200),
    group_status int,
    ad_id int,
    ad_name varchar(200),
    ad_utm_source varchar(200),
    ad_utm_medium varchar(200),
    ad_utm_campaign varchar(200),
    ad_utm_content varchar(200),
    impressions int,
    clicks int,
    cost float,
    conversions float,
    date date,
    account_name varchar(200),
    account_id int
)